// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css_Types$MyBlog from "./Css_Types.bs.js.js";

var aliceblue = Css_Types$MyBlog.Color.hex("F0F8FF");

var antiquewhite = Css_Types$MyBlog.Color.hex("FAEBD7");

var aqua = Css_Types$MyBlog.Color.hex("00FFFF");

var aquamarine = Css_Types$MyBlog.Color.hex("7FFFD4");

var azure = Css_Types$MyBlog.Color.hex("F0FFFF");

var beige = Css_Types$MyBlog.Color.hex("F5F5DC");

var bisque = Css_Types$MyBlog.Color.hex("FFE4C4");

var black = Css_Types$MyBlog.Color.hex("000000");

var blanchedalmond = Css_Types$MyBlog.Color.hex("FFEBCD");

var blue = Css_Types$MyBlog.Color.hex("0000FF");

var blueviolet = Css_Types$MyBlog.Color.hex("8A2BE2");

var brown = Css_Types$MyBlog.Color.hex("A52A2A");

var burlywood = Css_Types$MyBlog.Color.hex("DEB887");

var cadetblue = Css_Types$MyBlog.Color.hex("5F9EA0");

var chartreuse = Css_Types$MyBlog.Color.hex("7FFF00");

var chocolate = Css_Types$MyBlog.Color.hex("D2691E");

var coral = Css_Types$MyBlog.Color.hex("FF7F50");

var cornflowerblue = Css_Types$MyBlog.Color.hex("6495ED");

var cornsilk = Css_Types$MyBlog.Color.hex("FFF8DC");

var crimson = Css_Types$MyBlog.Color.hex("DC143C");

var cyan = Css_Types$MyBlog.Color.hex("00FFFF");

var darkblue = Css_Types$MyBlog.Color.hex("00008B");

var darkcyan = Css_Types$MyBlog.Color.hex("008B8B");

var darkgoldenrod = Css_Types$MyBlog.Color.hex("B8860B");

var darkgray = Css_Types$MyBlog.Color.hex("A9A9A9");

var darkgreen = Css_Types$MyBlog.Color.hex("006400");

var darkgrey = Css_Types$MyBlog.Color.hex("A9A9A9");

var darkkhaki = Css_Types$MyBlog.Color.hex("BDB76B");

var darkmagenta = Css_Types$MyBlog.Color.hex("8B008B");

var darkolivegreen = Css_Types$MyBlog.Color.hex("556B2F");

var darkorange = Css_Types$MyBlog.Color.hex("FF8C00");

var darkorchid = Css_Types$MyBlog.Color.hex("9932CC");

var darkred = Css_Types$MyBlog.Color.hex("8B0000");

var darksalmon = Css_Types$MyBlog.Color.hex("E9967A");

var darkseagreen = Css_Types$MyBlog.Color.hex("8FBC8F");

var darkslateblue = Css_Types$MyBlog.Color.hex("483D8B");

var darkslategray = Css_Types$MyBlog.Color.hex("2F4F4F");

var darkslategrey = Css_Types$MyBlog.Color.hex("2F4F4F");

var darkturquoise = Css_Types$MyBlog.Color.hex("00CED1");

var darkviolet = Css_Types$MyBlog.Color.hex("9400D3");

var deeppink = Css_Types$MyBlog.Color.hex("FF1493");

var deepskyblue = Css_Types$MyBlog.Color.hex("00BFFF");

var dimgray = Css_Types$MyBlog.Color.hex("696969");

var dimgrey = Css_Types$MyBlog.Color.hex("696969");

var dodgerblue = Css_Types$MyBlog.Color.hex("1E90FF");

var firebrick = Css_Types$MyBlog.Color.hex("B22222");

var floralwhite = Css_Types$MyBlog.Color.hex("FFFAF0");

var forestgreen = Css_Types$MyBlog.Color.hex("228B22");

var fuchsia = Css_Types$MyBlog.Color.hex("FF00FF");

var gainsboro = Css_Types$MyBlog.Color.hex("DCDCDC");

var ghostwhite = Css_Types$MyBlog.Color.hex("F8F8FF");

var gold = Css_Types$MyBlog.Color.hex("FFD700");

var goldenrod = Css_Types$MyBlog.Color.hex("DAA520");

var gray = Css_Types$MyBlog.Color.hex("808080");

var green = Css_Types$MyBlog.Color.hex("008000");

var greenyellow = Css_Types$MyBlog.Color.hex("ADFF2F");

var grey = Css_Types$MyBlog.Color.hex("808080");

var honeydew = Css_Types$MyBlog.Color.hex("F0FFF0");

var hotpink = Css_Types$MyBlog.Color.hex("FF69B4");

var indianred = Css_Types$MyBlog.Color.hex("CD5C5C");

var indigo = Css_Types$MyBlog.Color.hex("4B0082");

var ivory = Css_Types$MyBlog.Color.hex("FFFFF0");

var khaki = Css_Types$MyBlog.Color.hex("F0E68C");

var lavender = Css_Types$MyBlog.Color.hex("E6E6FA");

var lavenderblush = Css_Types$MyBlog.Color.hex("FFF0F5");

var lawngreen = Css_Types$MyBlog.Color.hex("7CFC00");

var lemonchiffon = Css_Types$MyBlog.Color.hex("FFFACD");

var lightblue = Css_Types$MyBlog.Color.hex("ADD8E6");

var lightcoral = Css_Types$MyBlog.Color.hex("F08080");

var lightcyan = Css_Types$MyBlog.Color.hex("E0FFFF");

var lightgoldenrodyellow = Css_Types$MyBlog.Color.hex("FAFAD2");

var lightgray = Css_Types$MyBlog.Color.hex("D3D3D3");

var lightgreen = Css_Types$MyBlog.Color.hex("90EE90");

var lightgrey = Css_Types$MyBlog.Color.hex("D3D3D3");

var lightpink = Css_Types$MyBlog.Color.hex("FFB6C1");

var lightsalmon = Css_Types$MyBlog.Color.hex("FFA07A");

var lightseagreen = Css_Types$MyBlog.Color.hex("20B2AA");

var lightskyblue = Css_Types$MyBlog.Color.hex("87CEFA");

var lightslategray = Css_Types$MyBlog.Color.hex("778899");

var lightslategrey = Css_Types$MyBlog.Color.hex("778899");

var lightsteelblue = Css_Types$MyBlog.Color.hex("B0C4DE");

var lightyellow = Css_Types$MyBlog.Color.hex("FFFFE0");

var lime = Css_Types$MyBlog.Color.hex("00FF00");

var limegreen = Css_Types$MyBlog.Color.hex("32CD32");

var linen = Css_Types$MyBlog.Color.hex("FAF0E6");

var magenta = Css_Types$MyBlog.Color.hex("FF00FF");

var maroon = Css_Types$MyBlog.Color.hex("800000");

var mediumaquamarine = Css_Types$MyBlog.Color.hex("66CDAA");

var mediumblue = Css_Types$MyBlog.Color.hex("0000CD");

var mediumorchid = Css_Types$MyBlog.Color.hex("BA55D3");

var mediumpurple = Css_Types$MyBlog.Color.hex("9370DB");

var mediumseagreen = Css_Types$MyBlog.Color.hex("3CB371");

var mediumslateblue = Css_Types$MyBlog.Color.hex("7B68EE");

var mediumspringgreen = Css_Types$MyBlog.Color.hex("00FA9A");

var mediumturquoise = Css_Types$MyBlog.Color.hex("48D1CC");

var mediumvioletred = Css_Types$MyBlog.Color.hex("C71585");

var midnightblue = Css_Types$MyBlog.Color.hex("191970");

var mintcream = Css_Types$MyBlog.Color.hex("F5FFFA");

var mistyrose = Css_Types$MyBlog.Color.hex("FFE4E1");

var moccasin = Css_Types$MyBlog.Color.hex("FFE4B5");

var navajowhite = Css_Types$MyBlog.Color.hex("FFDEAD");

var navy = Css_Types$MyBlog.Color.hex("000080");

var oldlace = Css_Types$MyBlog.Color.hex("FDF5E6");

var olive = Css_Types$MyBlog.Color.hex("808000");

var olivedrab = Css_Types$MyBlog.Color.hex("6B8E23");

var orange = Css_Types$MyBlog.Color.hex("FFA500");

var orangered = Css_Types$MyBlog.Color.hex("FF4500");

var orchid = Css_Types$MyBlog.Color.hex("DA70D6");

var palegoldenrod = Css_Types$MyBlog.Color.hex("EEE8AA");

var palegreen = Css_Types$MyBlog.Color.hex("98FB98");

var paleturquoise = Css_Types$MyBlog.Color.hex("AFEEEE");

var palevioletred = Css_Types$MyBlog.Color.hex("DB7093");

var papayawhip = Css_Types$MyBlog.Color.hex("FFEFD5");

var peachpuff = Css_Types$MyBlog.Color.hex("FFDAB9");

var peru = Css_Types$MyBlog.Color.hex("CD853F");

var pink = Css_Types$MyBlog.Color.hex("FFC0CB");

var plum = Css_Types$MyBlog.Color.hex("DDA0DD");

var powderblue = Css_Types$MyBlog.Color.hex("B0E0E6");

var purple = Css_Types$MyBlog.Color.hex("800080");

var rebeccapurple = Css_Types$MyBlog.Color.hex("663399");

var red = Css_Types$MyBlog.Color.hex("FF0000");

var rosybrown = Css_Types$MyBlog.Color.hex("BC8F8F");

var royalblue = Css_Types$MyBlog.Color.hex("4169E1");

var saddlebrown = Css_Types$MyBlog.Color.hex("8B4513");

var salmon = Css_Types$MyBlog.Color.hex("FA8072");

var sandybrown = Css_Types$MyBlog.Color.hex("F4A460");

var seagreen = Css_Types$MyBlog.Color.hex("2E8B57");

var seashell = Css_Types$MyBlog.Color.hex("FFF5EE");

var sienna = Css_Types$MyBlog.Color.hex("A0522D");

var silver = Css_Types$MyBlog.Color.hex("C0C0C0");

var skyblue = Css_Types$MyBlog.Color.hex("87CEEB");

var slateblue = Css_Types$MyBlog.Color.hex("6A5ACD");

var slategray = Css_Types$MyBlog.Color.hex("708090");

var slategrey = Css_Types$MyBlog.Color.hex("708090");

var snow = Css_Types$MyBlog.Color.hex("FFFAFA");

var springgreen = Css_Types$MyBlog.Color.hex("00FF7F");

var steelblue = Css_Types$MyBlog.Color.hex("4682B4");

var tan = Css_Types$MyBlog.Color.hex("D2B48C");

var teal = Css_Types$MyBlog.Color.hex("008080");

var thistle = Css_Types$MyBlog.Color.hex("D8BFD8");

var tomato = Css_Types$MyBlog.Color.hex("FF6347");

var turquoise = Css_Types$MyBlog.Color.hex("40E0D0");

var violet = Css_Types$MyBlog.Color.hex("EE82EE");

var wheat = Css_Types$MyBlog.Color.hex("F5DEB3");

var white = Css_Types$MyBlog.Color.hex("FFFFFF");

var whitesmoke = Css_Types$MyBlog.Color.hex("F5F5F5");

var yellow = Css_Types$MyBlog.Color.hex("FFFF00");

var yellowgreen = Css_Types$MyBlog.Color.hex("9ACD3");

var transparent = Css_Types$MyBlog.Color.transparent;

export {
  aliceblue ,
  antiquewhite ,
  aqua ,
  aquamarine ,
  azure ,
  beige ,
  bisque ,
  black ,
  blanchedalmond ,
  blue ,
  blueviolet ,
  brown ,
  burlywood ,
  cadetblue ,
  chartreuse ,
  chocolate ,
  coral ,
  cornflowerblue ,
  cornsilk ,
  crimson ,
  cyan ,
  darkblue ,
  darkcyan ,
  darkgoldenrod ,
  darkgray ,
  darkgreen ,
  darkgrey ,
  darkkhaki ,
  darkmagenta ,
  darkolivegreen ,
  darkorange ,
  darkorchid ,
  darkred ,
  darksalmon ,
  darkseagreen ,
  darkslateblue ,
  darkslategray ,
  darkslategrey ,
  darkturquoise ,
  darkviolet ,
  deeppink ,
  deepskyblue ,
  dimgray ,
  dimgrey ,
  dodgerblue ,
  firebrick ,
  floralwhite ,
  forestgreen ,
  fuchsia ,
  gainsboro ,
  ghostwhite ,
  gold ,
  goldenrod ,
  gray ,
  green ,
  greenyellow ,
  grey ,
  honeydew ,
  hotpink ,
  indianred ,
  indigo ,
  ivory ,
  khaki ,
  lavender ,
  lavenderblush ,
  lawngreen ,
  lemonchiffon ,
  lightblue ,
  lightcoral ,
  lightcyan ,
  lightgoldenrodyellow ,
  lightgray ,
  lightgreen ,
  lightgrey ,
  lightpink ,
  lightsalmon ,
  lightseagreen ,
  lightskyblue ,
  lightslategray ,
  lightslategrey ,
  lightsteelblue ,
  lightyellow ,
  lime ,
  limegreen ,
  linen ,
  magenta ,
  maroon ,
  mediumaquamarine ,
  mediumblue ,
  mediumorchid ,
  mediumpurple ,
  mediumseagreen ,
  mediumslateblue ,
  mediumspringgreen ,
  mediumturquoise ,
  mediumvioletred ,
  midnightblue ,
  mintcream ,
  mistyrose ,
  moccasin ,
  navajowhite ,
  navy ,
  oldlace ,
  olive ,
  olivedrab ,
  orange ,
  orangered ,
  orchid ,
  palegoldenrod ,
  palegreen ,
  paleturquoise ,
  palevioletred ,
  papayawhip ,
  peachpuff ,
  peru ,
  pink ,
  plum ,
  powderblue ,
  purple ,
  rebeccapurple ,
  red ,
  rosybrown ,
  royalblue ,
  saddlebrown ,
  salmon ,
  sandybrown ,
  seagreen ,
  seashell ,
  sienna ,
  silver ,
  skyblue ,
  slateblue ,
  slategray ,
  slategrey ,
  snow ,
  springgreen ,
  steelblue ,
  tan ,
  teal ,
  thistle ,
  tomato ,
  turquoise ,
  violet ,
  wheat ,
  white ,
  whitesmoke ,
  yellow ,
  yellowgreen ,
  transparent ,

}
/* aliceblue Not a pure module */
