// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as BsCss_Types$MyBlog from "./BsCss_Types.bs.js";

var aliceblue = BsCss_Types$MyBlog.Color.hex("F0F8FF");

var antiquewhite = BsCss_Types$MyBlog.Color.hex("FAEBD7");

var aqua = BsCss_Types$MyBlog.Color.hex("00FFFF");

var aquamarine = BsCss_Types$MyBlog.Color.hex("7FFFD4");

var azure = BsCss_Types$MyBlog.Color.hex("F0FFFF");

var beige = BsCss_Types$MyBlog.Color.hex("F5F5DC");

var bisque = BsCss_Types$MyBlog.Color.hex("FFE4C4");

var black = BsCss_Types$MyBlog.Color.hex("000000");

var blanchedalmond = BsCss_Types$MyBlog.Color.hex("FFEBCD");

var blue = BsCss_Types$MyBlog.Color.hex("0000FF");

var blueviolet = BsCss_Types$MyBlog.Color.hex("8A2BE2");

var brown = BsCss_Types$MyBlog.Color.hex("A52A2A");

var burlywood = BsCss_Types$MyBlog.Color.hex("DEB887");

var cadetblue = BsCss_Types$MyBlog.Color.hex("5F9EA0");

var chartreuse = BsCss_Types$MyBlog.Color.hex("7FFF00");

var chocolate = BsCss_Types$MyBlog.Color.hex("D2691E");

var coral = BsCss_Types$MyBlog.Color.hex("FF7F50");

var cornflowerblue = BsCss_Types$MyBlog.Color.hex("6495ED");

var cornsilk = BsCss_Types$MyBlog.Color.hex("FFF8DC");

var crimson = BsCss_Types$MyBlog.Color.hex("DC143C");

var cyan = BsCss_Types$MyBlog.Color.hex("00FFFF");

var darkblue = BsCss_Types$MyBlog.Color.hex("00008B");

var darkcyan = BsCss_Types$MyBlog.Color.hex("008B8B");

var darkgoldenrod = BsCss_Types$MyBlog.Color.hex("B8860B");

var darkgray = BsCss_Types$MyBlog.Color.hex("A9A9A9");

var darkgreen = BsCss_Types$MyBlog.Color.hex("006400");

var darkgrey = BsCss_Types$MyBlog.Color.hex("A9A9A9");

var darkkhaki = BsCss_Types$MyBlog.Color.hex("BDB76B");

var darkmagenta = BsCss_Types$MyBlog.Color.hex("8B008B");

var darkolivegreen = BsCss_Types$MyBlog.Color.hex("556B2F");

var darkorange = BsCss_Types$MyBlog.Color.hex("FF8C00");

var darkorchid = BsCss_Types$MyBlog.Color.hex("9932CC");

var darkred = BsCss_Types$MyBlog.Color.hex("8B0000");

var darksalmon = BsCss_Types$MyBlog.Color.hex("E9967A");

var darkseagreen = BsCss_Types$MyBlog.Color.hex("8FBC8F");

var darkslateblue = BsCss_Types$MyBlog.Color.hex("483D8B");

var darkslategray = BsCss_Types$MyBlog.Color.hex("2F4F4F");

var darkslategrey = BsCss_Types$MyBlog.Color.hex("2F4F4F");

var darkturquoise = BsCss_Types$MyBlog.Color.hex("00CED1");

var darkviolet = BsCss_Types$MyBlog.Color.hex("9400D3");

var deeppink = BsCss_Types$MyBlog.Color.hex("FF1493");

var deepskyblue = BsCss_Types$MyBlog.Color.hex("00BFFF");

var dimgray = BsCss_Types$MyBlog.Color.hex("696969");

var dimgrey = BsCss_Types$MyBlog.Color.hex("696969");

var dodgerblue = BsCss_Types$MyBlog.Color.hex("1E90FF");

var firebrick = BsCss_Types$MyBlog.Color.hex("B22222");

var floralwhite = BsCss_Types$MyBlog.Color.hex("FFFAF0");

var forestgreen = BsCss_Types$MyBlog.Color.hex("228B22");

var fuchsia = BsCss_Types$MyBlog.Color.hex("FF00FF");

var gainsboro = BsCss_Types$MyBlog.Color.hex("DCDCDC");

var ghostwhite = BsCss_Types$MyBlog.Color.hex("F8F8FF");

var gold = BsCss_Types$MyBlog.Color.hex("FFD700");

var goldenrod = BsCss_Types$MyBlog.Color.hex("DAA520");

var gray = BsCss_Types$MyBlog.Color.hex("808080");

var green = BsCss_Types$MyBlog.Color.hex("008000");

var greenyellow = BsCss_Types$MyBlog.Color.hex("ADFF2F");

var grey = BsCss_Types$MyBlog.Color.hex("808080");

var honeydew = BsCss_Types$MyBlog.Color.hex("F0FFF0");

var hotpink = BsCss_Types$MyBlog.Color.hex("FF69B4");

var indianred = BsCss_Types$MyBlog.Color.hex("CD5C5C");

var indigo = BsCss_Types$MyBlog.Color.hex("4B0082");

var ivory = BsCss_Types$MyBlog.Color.hex("FFFFF0");

var khaki = BsCss_Types$MyBlog.Color.hex("F0E68C");

var lavender = BsCss_Types$MyBlog.Color.hex("E6E6FA");

var lavenderblush = BsCss_Types$MyBlog.Color.hex("FFF0F5");

var lawngreen = BsCss_Types$MyBlog.Color.hex("7CFC00");

var lemonchiffon = BsCss_Types$MyBlog.Color.hex("FFFACD");

var lightblue = BsCss_Types$MyBlog.Color.hex("ADD8E6");

var lightcoral = BsCss_Types$MyBlog.Color.hex("F08080");

var lightcyan = BsCss_Types$MyBlog.Color.hex("E0FFFF");

var lightgoldenrodyellow = BsCss_Types$MyBlog.Color.hex("FAFAD2");

var lightgray = BsCss_Types$MyBlog.Color.hex("D3D3D3");

var lightgreen = BsCss_Types$MyBlog.Color.hex("90EE90");

var lightgrey = BsCss_Types$MyBlog.Color.hex("D3D3D3");

var lightpink = BsCss_Types$MyBlog.Color.hex("FFB6C1");

var lightsalmon = BsCss_Types$MyBlog.Color.hex("FFA07A");

var lightseagreen = BsCss_Types$MyBlog.Color.hex("20B2AA");

var lightskyblue = BsCss_Types$MyBlog.Color.hex("87CEFA");

var lightslategray = BsCss_Types$MyBlog.Color.hex("778899");

var lightslategrey = BsCss_Types$MyBlog.Color.hex("778899");

var lightsteelblue = BsCss_Types$MyBlog.Color.hex("B0C4DE");

var lightyellow = BsCss_Types$MyBlog.Color.hex("FFFFE0");

var lime = BsCss_Types$MyBlog.Color.hex("00FF00");

var limegreen = BsCss_Types$MyBlog.Color.hex("32CD32");

var linen = BsCss_Types$MyBlog.Color.hex("FAF0E6");

var magenta = BsCss_Types$MyBlog.Color.hex("FF00FF");

var maroon = BsCss_Types$MyBlog.Color.hex("800000");

var mediumaquamarine = BsCss_Types$MyBlog.Color.hex("66CDAA");

var mediumblue = BsCss_Types$MyBlog.Color.hex("0000CD");

var mediumorchid = BsCss_Types$MyBlog.Color.hex("BA55D3");

var mediumpurple = BsCss_Types$MyBlog.Color.hex("9370DB");

var mediumseagreen = BsCss_Types$MyBlog.Color.hex("3CB371");

var mediumslateblue = BsCss_Types$MyBlog.Color.hex("7B68EE");

var mediumspringgreen = BsCss_Types$MyBlog.Color.hex("00FA9A");

var mediumturquoise = BsCss_Types$MyBlog.Color.hex("48D1CC");

var mediumvioletred = BsCss_Types$MyBlog.Color.hex("C71585");

var midnightblue = BsCss_Types$MyBlog.Color.hex("191970");

var mintcream = BsCss_Types$MyBlog.Color.hex("F5FFFA");

var mistyrose = BsCss_Types$MyBlog.Color.hex("FFE4E1");

var moccasin = BsCss_Types$MyBlog.Color.hex("FFE4B5");

var navajowhite = BsCss_Types$MyBlog.Color.hex("FFDEAD");

var navy = BsCss_Types$MyBlog.Color.hex("000080");

var oldlace = BsCss_Types$MyBlog.Color.hex("FDF5E6");

var olive = BsCss_Types$MyBlog.Color.hex("808000");

var olivedrab = BsCss_Types$MyBlog.Color.hex("6B8E23");

var orange = BsCss_Types$MyBlog.Color.hex("FFA500");

var orangered = BsCss_Types$MyBlog.Color.hex("FF4500");

var orchid = BsCss_Types$MyBlog.Color.hex("DA70D6");

var palegoldenrod = BsCss_Types$MyBlog.Color.hex("EEE8AA");

var palegreen = BsCss_Types$MyBlog.Color.hex("98FB98");

var paleturquoise = BsCss_Types$MyBlog.Color.hex("AFEEEE");

var palevioletred = BsCss_Types$MyBlog.Color.hex("DB7093");

var papayawhip = BsCss_Types$MyBlog.Color.hex("FFEFD5");

var peachpuff = BsCss_Types$MyBlog.Color.hex("FFDAB9");

var peru = BsCss_Types$MyBlog.Color.hex("CD853F");

var pink = BsCss_Types$MyBlog.Color.hex("FFC0CB");

var plum = BsCss_Types$MyBlog.Color.hex("DDA0DD");

var powderblue = BsCss_Types$MyBlog.Color.hex("B0E0E6");

var purple = BsCss_Types$MyBlog.Color.hex("800080");

var rebeccapurple = BsCss_Types$MyBlog.Color.hex("663399");

var red = BsCss_Types$MyBlog.Color.hex("FF0000");

var rosybrown = BsCss_Types$MyBlog.Color.hex("BC8F8F");

var royalblue = BsCss_Types$MyBlog.Color.hex("4169E1");

var saddlebrown = BsCss_Types$MyBlog.Color.hex("8B4513");

var salmon = BsCss_Types$MyBlog.Color.hex("FA8072");

var sandybrown = BsCss_Types$MyBlog.Color.hex("F4A460");

var seagreen = BsCss_Types$MyBlog.Color.hex("2E8B57");

var seashell = BsCss_Types$MyBlog.Color.hex("FFF5EE");

var sienna = BsCss_Types$MyBlog.Color.hex("A0522D");

var silver = BsCss_Types$MyBlog.Color.hex("C0C0C0");

var skyblue = BsCss_Types$MyBlog.Color.hex("87CEEB");

var slateblue = BsCss_Types$MyBlog.Color.hex("6A5ACD");

var slategray = BsCss_Types$MyBlog.Color.hex("708090");

var slategrey = BsCss_Types$MyBlog.Color.hex("708090");

var snow = BsCss_Types$MyBlog.Color.hex("FFFAFA");

var springgreen = BsCss_Types$MyBlog.Color.hex("00FF7F");

var steelblue = BsCss_Types$MyBlog.Color.hex("4682B4");

var tan = BsCss_Types$MyBlog.Color.hex("D2B48C");

var teal = BsCss_Types$MyBlog.Color.hex("008080");

var thistle = BsCss_Types$MyBlog.Color.hex("D8BFD8");

var tomato = BsCss_Types$MyBlog.Color.hex("FF6347");

var turquoise = BsCss_Types$MyBlog.Color.hex("40E0D0");

var violet = BsCss_Types$MyBlog.Color.hex("EE82EE");

var wheat = BsCss_Types$MyBlog.Color.hex("F5DEB3");

var white = BsCss_Types$MyBlog.Color.hex("FFFFFF");

var whitesmoke = BsCss_Types$MyBlog.Color.hex("F5F5F5");

var yellow = BsCss_Types$MyBlog.Color.hex("FFFF00");

var yellowgreen = BsCss_Types$MyBlog.Color.hex("9ACD3");

var transparent = BsCss_Types$MyBlog.Color.transparent;

export {
  aliceblue ,
  antiquewhite ,
  aqua ,
  aquamarine ,
  azure ,
  beige ,
  bisque ,
  black ,
  blanchedalmond ,
  blue ,
  blueviolet ,
  brown ,
  burlywood ,
  cadetblue ,
  chartreuse ,
  chocolate ,
  coral ,
  cornflowerblue ,
  cornsilk ,
  crimson ,
  cyan ,
  darkblue ,
  darkcyan ,
  darkgoldenrod ,
  darkgray ,
  darkgreen ,
  darkgrey ,
  darkkhaki ,
  darkmagenta ,
  darkolivegreen ,
  darkorange ,
  darkorchid ,
  darkred ,
  darksalmon ,
  darkseagreen ,
  darkslateblue ,
  darkslategray ,
  darkslategrey ,
  darkturquoise ,
  darkviolet ,
  deeppink ,
  deepskyblue ,
  dimgray ,
  dimgrey ,
  dodgerblue ,
  firebrick ,
  floralwhite ,
  forestgreen ,
  fuchsia ,
  gainsboro ,
  ghostwhite ,
  gold ,
  goldenrod ,
  gray ,
  green ,
  greenyellow ,
  grey ,
  honeydew ,
  hotpink ,
  indianred ,
  indigo ,
  ivory ,
  khaki ,
  lavender ,
  lavenderblush ,
  lawngreen ,
  lemonchiffon ,
  lightblue ,
  lightcoral ,
  lightcyan ,
  lightgoldenrodyellow ,
  lightgray ,
  lightgreen ,
  lightgrey ,
  lightpink ,
  lightsalmon ,
  lightseagreen ,
  lightskyblue ,
  lightslategray ,
  lightslategrey ,
  lightsteelblue ,
  lightyellow ,
  lime ,
  limegreen ,
  linen ,
  magenta ,
  maroon ,
  mediumaquamarine ,
  mediumblue ,
  mediumorchid ,
  mediumpurple ,
  mediumseagreen ,
  mediumslateblue ,
  mediumspringgreen ,
  mediumturquoise ,
  mediumvioletred ,
  midnightblue ,
  mintcream ,
  mistyrose ,
  moccasin ,
  navajowhite ,
  navy ,
  oldlace ,
  olive ,
  olivedrab ,
  orange ,
  orangered ,
  orchid ,
  palegoldenrod ,
  palegreen ,
  paleturquoise ,
  palevioletred ,
  papayawhip ,
  peachpuff ,
  peru ,
  pink ,
  plum ,
  powderblue ,
  purple ,
  rebeccapurple ,
  red ,
  rosybrown ,
  royalblue ,
  saddlebrown ,
  salmon ,
  sandybrown ,
  seagreen ,
  seashell ,
  sienna ,
  silver ,
  skyblue ,
  slateblue ,
  slategray ,
  slategrey ,
  snow ,
  springgreen ,
  steelblue ,
  tan ,
  teal ,
  thistle ,
  tomato ,
  turquoise ,
  violet ,
  wheat ,
  white ,
  whitesmoke ,
  yellow ,
  yellowgreen ,
  transparent ,
  
}
/* aliceblue Not a pure module */
